### PR TITLE
Add new tests for existing calc modes.

### PR DESCRIPTION
**Pull request by ltan01**
Hello,

I added and updated tests in the testsuite for all of the calc modes except dynamics-pp and dynamics-run. I also added more tests for plot_tools.py. Some of the calc modes don't have any functions besides initializing (trans, imsigma) but I included a test script and corresponding reference for those modes.

### CODE REVIEW

**Comment by imaliyov** [comment]
Great work Laurie!

For plotting tests, do we actually test the PDF generated? If we do, I do not recommend this. We were trying a lot previously and it was always unstable and hardly reproducible. 

I even suggest we remove any PDF testing from the current testsuite, because sooner or later they will break.

**Comment by ltan01** [comment]
> Great work Laurie!
> 
> For plotting tests, do we actually test the PDF generated? If we do, I do not recommend this. We were trying a lot previously and it was always unstable and hardly reproducible.
> 
> I even suggest we remove any PDF testing from the current testsuite, because sooner or later they will break.

Thank you, Ivan!

No, I do not test the PDF generated for any of the plotting tests. I followed the format for test_plot_dispersion() in test_plot_tools.py, where the function is called but no files are generated.

**Comment by imaliyov** [comment]
> > Great work Laurie!
> > For plotting tests, do we actually test the PDF generated? If we do, I do not recommend this. We were trying a lot previously and it was always unstable and hardly reproducible.
> > I even suggest we remove any PDF testing from the current testsuite, because sooner or later they will break.
> 
> Thank you, Ivan!
> 
> No, I do not test the PDF generated for any of the plotting tests. I followed the format for test_plot_dispersion() in test_plot_tools.py, where the function is called but no files are generated.

Sounds good!

Why do we have tests failing, for example, with errors like this one:

```
ERROR test_spins_calc_mode.py::test_plot_spins[1-True-False] - AttributeError: module 'perturbopy.postproc' has no attribute 'Spins'
```

**Comment by ltan01** [comment]
> > > Great work Laurie!
> > > For plotting tests, do we actually test the PDF generated? If we do, I do not recommend this. We were trying a lot previously and it was always unstable and hardly reproducible.
> > > I even suggest we remove any PDF testing from the current testsuite, because sooner or later they will break.
> > 
> > 
> > Thank you, Ivan!
> > No, I do not test the PDF generated for any of the plotting tests. I followed the format for test_plot_dispersion() in test_plot_tools.py, where the function is called but no files are generated.
> 
> Sounds good!
> 
> Why do we have tests failing, for example, with errors like this one:
> 
> ```
> ERROR test_spins_calc_mode.py::test_plot_spins[1-True-False] - AttributeError: module 'perturbopy.postproc' has no attribute 'Spins'
> ```

I included tests for the spin calc modes! This branch is based off the main branch that doesn’t have those calc modes yet. The error message should go away once my PR for the spin calc modes is approved and the spin branch is merged.

**Comment by imaliyov** [comment]
I think the correct way would be to create another branch from the one where the spin calc mode is implemented and put tests there, then create a pull request.

Otherwise, bypassing the github tests is a bad practice. We created them exactly for this reason - to check if the new implementation works.

**Comment by ltan01** [comment]
Ok, thank you all for your feedback! I'll split them into two PRs with the right branches for each one :)

**Review by hurricane642 — APPROVED** [review]
LGTM
Great work, thank you!
